// flow-typed signature: 65aa9e205df3d4745a3fc3f6523d8e9d
// flow-typed version: <<STUB>>/publish_v^0.6.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'publish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'publish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'publish/bin/publish' {
  declare module.exports: any;
}

declare module 'publish/test/basic' {
  declare module.exports: any;
}

declare module 'publish/test/outside-in' {
  declare module.exports: any;
}

// Filename aliases
declare module 'publish/bin/publish.js' {
  declare module.exports: $Exports<'publish/bin/publish'>;
}
declare module 'publish/index' {
  declare module.exports: $Exports<'publish'>;
}
declare module 'publish/index.js' {
  declare module.exports: $Exports<'publish'>;
}
declare module 'publish/test/basic.js' {
  declare module.exports: $Exports<'publish/test/basic'>;
}
declare module 'publish/test/outside-in.js' {
  declare module.exports: $Exports<'publish/test/outside-in'>;
}
